[project]
name = "storytelling"
version = "0.1.0"
description = "storytelling using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.105.0,<1.0.0"
]

[project.scripts]
storytelling = "storytelling.main:run"
run_crew = "storytelling.main:run"
train = "storytelling.main:train"
replay = "storytelling.main:replay"
test = "storytelling.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
